# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "paris-saclay-thesis-flat"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Sébastien Mestrallet <@sebmestrallet>"]
license = "MIT-0"
description = "An unofficial, flat-design template for Paris-Saclay University theses"
repository = "https://github.com/sebmestrallet/typst-paris-saclay-thesis-flat"
keywords = ["thesis", "Paris-Saclay"]
categories = ["thesis"]
disciplines = []
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnails/p1.png"

